[functions]
  node_bundler = "esbuild"
[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/media/pictures", # Eleventy Image Disk Cache
    ".cache", # Remote Asset Cache
    "src/_data/posts.json" # index file for the bots
  ]
